### ISSUE TITLE
[Request] Link to paper

### ISSUE THREAD

**Issue by bishshoy** [rickgroen/morphpool#1]
Hi Rick,

I am interested in your paper (MorphPool: Efficient Non-linear Pooling & Unpooling in CNNs). Can you share the PDF?

Thanks.

**Comment by rickgroen** [comment]
Hi Bishshoy,

Thanks for your interest!
There is no link to the paper available yet, since BMVC will make public the accepted papers in their proceedings. BMVC is held 21-24 November this year. I expect they will make available the papers during or shortly after this period.
In the mean time, I am finalizing the public code to upload it by the time the papers go live.

I will comment on your issue (with a link to the paper) as soon as BMVC publishes their proceedings.

Best regards,
Rick

**Comment by rickgroen** [comment]
Hi Bishshoy, here is the link to the paper: https://bmvc2022.mpi-inf.mpg.de/56/
